apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.name" . }}-helm-deployment
  namespace: default
  labels:
    app: {{ include "hello-world.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-world.name" . }}
      type: backend
  template:
    metadata:
      labels:
        app: {{ include "hello-world.name" . }}
        type: backend
    spec:
      containers:
      - name: {{ include "hello-world.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      imagePullSecrets:
      - name: dockercred

